runtime: java
env: flex
#runtime_config:
#  jdk: openjdk8
#handlers:
#  - url: /.*
#    script: this field is required, but ignored

#runtime: java
#env: flex
#
#handlers:
#  - url: /.*
#    script: this field is required, but ignored

#runtime: java11
#instance_class: F2
#env_variables:
#  SPRING_PROFILES_ACTIVE: "prod"
#entrypoint: java -noverify -jar demo-0.0.1-SNAPSHOT.jar